### ISSUE TITLE
Cannot close inside quotes

### ISSUE THREAD

**Issue by chunkhang** [tmsvg/pear-tree#52] opened 2020-10-15 05:03 UTC
When inside quotes, entering `{` does not trigger the closer `}`. 

Expected:
```
"|"
"{|}"
```

Actual:
```
"|"
"{|"
```

**Comment by tmsvg** [comment] 2024-11-02 21:37
This is expected behavior, though I could potentially add an option to change the behavior. Closing as duplicate of https://github.com/tmsvg/pear-tree/issues/19

**Closed** 2024-11-02 21:48 UTC
